platform :ios, '8.0'

target ‘douTu’ do

pod "AFNetworking"
pod "SDWebImage"
pod "SVProgressHUD"
pod "MJExtension"
pod "MJRefresh"
pod 'NJKWebViewProgress'
pod 'Masonry'
pod ‘UMengUShare/UI’
pod ‘UMengUShare/Social/WeChat'
pod ‘UMengUShare/Social/QQ'

end
